//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        double Suma(double nro1, double nro2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SumaAsync(double nro1, double nro2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resta", ReplyAction="*")]
        double Resta(double nro1, double nro2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resta", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RestaAsync(double nro1, double nro2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacion", ReplyAction="*")]
        double Multiplicacion(double nro1, double nro2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacion", ReplyAction="*")]
        System.Threading.Tasks.Task<double> MultiplicacionAsync(double nro1, double nro2);
        
        // CODEGEN: Generating message contract since element name DivisionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        WebApplication2.ServiceReference1.DivisionResponse Division(WebApplication2.ServiceReference1.DivisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.DivisionResponse> DivisionAsync(WebApplication2.ServiceReference1.DivisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inverso", ReplyAction="*")]
        double Inverso(double nro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inverso", ReplyAction="*")]
        System.Threading.Tasks.Task<double> InversoAsync(double nro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Factorial", ReplyAction="*")]
        double Factorial(int nro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Factorial", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FactorialAsync(int nro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Potencia", ReplyAction="*")]
        double Potencia(double nro1, double nro2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Potencia", ReplyAction="*")]
        System.Threading.Tasks.Task<double> PotenciaAsync(double nro1, double nro2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Seno", ReplyAction="*")]
        double Seno(double nro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Seno", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SenoAsync(double nro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Coseno", ReplyAction="*")]
        double Coseno(double nro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Coseno", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CosenoAsync(double nro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tangente", ReplyAction="*")]
        double Tangente(double nro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tangente", ReplyAction="*")]
        System.Threading.Tasks.Task<double> TangenteAsync(double nro);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Division", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.DivisionRequestBody Body;
        
        public DivisionRequest() {
        }
        
        public DivisionRequest(WebApplication2.ServiceReference1.DivisionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DivisionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double nro1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double nro2;
        
        public DivisionRequestBody() {
        }
        
        public DivisionRequestBody(double nro1, double nro2) {
            this.nro1 = nro1;
            this.nro2 = nro2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DivisionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.DivisionResponseBody Body;
        
        public DivisionResponse() {
        }
        
        public DivisionResponse(WebApplication2.ServiceReference1.DivisionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DivisionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DivisionResult;
        
        public DivisionResponseBody() {
        }
        
        public DivisionResponseBody(string DivisionResult) {
            this.DivisionResult = DivisionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication2.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication2.ServiceReference1.WebService1Soap>, WebApplication2.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Suma(double nro1, double nro2) {
            return base.Channel.Suma(nro1, nro2);
        }
        
        public System.Threading.Tasks.Task<double> SumaAsync(double nro1, double nro2) {
            return base.Channel.SumaAsync(nro1, nro2);
        }
        
        public double Resta(double nro1, double nro2) {
            return base.Channel.Resta(nro1, nro2);
        }
        
        public System.Threading.Tasks.Task<double> RestaAsync(double nro1, double nro2) {
            return base.Channel.RestaAsync(nro1, nro2);
        }
        
        public double Multiplicacion(double nro1, double nro2) {
            return base.Channel.Multiplicacion(nro1, nro2);
        }
        
        public System.Threading.Tasks.Task<double> MultiplicacionAsync(double nro1, double nro2) {
            return base.Channel.MultiplicacionAsync(nro1, nro2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.DivisionResponse WebApplication2.ServiceReference1.WebService1Soap.Division(WebApplication2.ServiceReference1.DivisionRequest request) {
            return base.Channel.Division(request);
        }
        
        public string Division(double nro1, double nro2) {
            WebApplication2.ServiceReference1.DivisionRequest inValue = new WebApplication2.ServiceReference1.DivisionRequest();
            inValue.Body = new WebApplication2.ServiceReference1.DivisionRequestBody();
            inValue.Body.nro1 = nro1;
            inValue.Body.nro2 = nro2;
            WebApplication2.ServiceReference1.DivisionResponse retVal = ((WebApplication2.ServiceReference1.WebService1Soap)(this)).Division(inValue);
            return retVal.Body.DivisionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.DivisionResponse> WebApplication2.ServiceReference1.WebService1Soap.DivisionAsync(WebApplication2.ServiceReference1.DivisionRequest request) {
            return base.Channel.DivisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.DivisionResponse> DivisionAsync(double nro1, double nro2) {
            WebApplication2.ServiceReference1.DivisionRequest inValue = new WebApplication2.ServiceReference1.DivisionRequest();
            inValue.Body = new WebApplication2.ServiceReference1.DivisionRequestBody();
            inValue.Body.nro1 = nro1;
            inValue.Body.nro2 = nro2;
            return ((WebApplication2.ServiceReference1.WebService1Soap)(this)).DivisionAsync(inValue);
        }
        
        public double Inverso(double nro) {
            return base.Channel.Inverso(nro);
        }
        
        public System.Threading.Tasks.Task<double> InversoAsync(double nro) {
            return base.Channel.InversoAsync(nro);
        }
        
        public double Factorial(int nro) {
            return base.Channel.Factorial(nro);
        }
        
        public System.Threading.Tasks.Task<double> FactorialAsync(int nro) {
            return base.Channel.FactorialAsync(nro);
        }
        
        public double Potencia(double nro1, double nro2) {
            return base.Channel.Potencia(nro1, nro2);
        }
        
        public System.Threading.Tasks.Task<double> PotenciaAsync(double nro1, double nro2) {
            return base.Channel.PotenciaAsync(nro1, nro2);
        }
        
        public double Seno(double nro) {
            return base.Channel.Seno(nro);
        }
        
        public System.Threading.Tasks.Task<double> SenoAsync(double nro) {
            return base.Channel.SenoAsync(nro);
        }
        
        public double Coseno(double nro) {
            return base.Channel.Coseno(nro);
        }
        
        public System.Threading.Tasks.Task<double> CosenoAsync(double nro) {
            return base.Channel.CosenoAsync(nro);
        }
        
        public double Tangente(double nro) {
            return base.Channel.Tangente(nro);
        }
        
        public System.Threading.Tasks.Task<double> TangenteAsync(double nro) {
            return base.Channel.TangenteAsync(nro);
        }
    }
}
