'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Suma", ReplyAction:="*")>  _
        Function Suma(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Suma", ReplyAction:="*")>  _
        Function SumaAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function Resta(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function RestaAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicacion", ReplyAction:="*")>  _
        Function Multiplicacion(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicacion", ReplyAction:="*")>  _
        Function MultiplicacionAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        'CODEGEN: Generating message contract since element name DivisionResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Division", ReplyAction:="*")>  _
        Function Division(ByVal request As ServiceReference1.DivisionRequest) As ServiceReference1.DivisionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Division", ReplyAction:="*")>  _
        Function DivisionAsync(ByVal request As ServiceReference1.DivisionRequest) As System.Threading.Tasks.Task(Of ServiceReference1.DivisionResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Inverso", ReplyAction:="*")>  _
        Function Inverso(ByVal nro As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Inverso", ReplyAction:="*")>  _
        Function InversoAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Factorial", ReplyAction:="*")>  _
        Function Factorial(ByVal nro As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Factorial", ReplyAction:="*")>  _
        Function FactorialAsync(ByVal nro As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Potencia", ReplyAction:="*")>  _
        Function Potencia(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Potencia", ReplyAction:="*")>  _
        Function PotenciaAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function Seno(ByVal nro As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function SenoAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Coseno", ReplyAction:="*")>  _
        Function Coseno(ByVal nro As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Coseno", ReplyAction:="*")>  _
        Function CosenoAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Tangente", ReplyAction:="*")>  _
        Function Tangente(ByVal nro As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Tangente", ReplyAction:="*")>  _
        Function TangenteAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DivisionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Division", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.DivisionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.DivisionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DivisionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public nro1 As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nro2 As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nro1 As Double, ByVal nro2 As Double)
            MyBase.New
            Me.nro1 = nro1
            Me.nro2 = nro2
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DivisionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DivisionResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.DivisionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.DivisionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DivisionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public DivisionResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DivisionResult As String)
            MyBase.New
            Me.DivisionResult = DivisionResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Suma(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.Suma
            Return MyBase.Channel.Suma(nro1, nro2)
        End Function
        
        Public Function SumaAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.SumaAsync
            Return MyBase.Channel.SumaAsync(nro1, nro2)
        End Function
        
        Public Function Resta(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.Resta
            Return MyBase.Channel.Resta(nro1, nro2)
        End Function
        
        Public Function RestaAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.RestaAsync
            Return MyBase.Channel.RestaAsync(nro1, nro2)
        End Function
        
        Public Function Multiplicacion(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.Multiplicacion
            Return MyBase.Channel.Multiplicacion(nro1, nro2)
        End Function
        
        Public Function MultiplicacionAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.MultiplicacionAsync
            Return MyBase.Channel.MultiplicacionAsync(nro1, nro2)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_Division(ByVal request As ServiceReference1.DivisionRequest) As ServiceReference1.DivisionResponse Implements ServiceReference1.WebService1Soap.Division
            Return MyBase.Channel.Division(request)
        End Function
        
        Public Function Division(ByVal nro1 As Double, ByVal nro2 As Double) As String
            Dim inValue As ServiceReference1.DivisionRequest = New ServiceReference1.DivisionRequest()
            inValue.Body = New ServiceReference1.DivisionRequestBody()
            inValue.Body.nro1 = nro1
            inValue.Body.nro2 = nro2
            Dim retVal As ServiceReference1.DivisionResponse = CType(Me,ServiceReference1.WebService1Soap).Division(inValue)
            Return retVal.Body.DivisionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_DivisionAsync(ByVal request As ServiceReference1.DivisionRequest) As System.Threading.Tasks.Task(Of ServiceReference1.DivisionResponse) Implements ServiceReference1.WebService1Soap.DivisionAsync
            Return MyBase.Channel.DivisionAsync(request)
        End Function
        
        Public Function DivisionAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of ServiceReference1.DivisionResponse)
            Dim inValue As ServiceReference1.DivisionRequest = New ServiceReference1.DivisionRequest()
            inValue.Body = New ServiceReference1.DivisionRequestBody()
            inValue.Body.nro1 = nro1
            inValue.Body.nro2 = nro2
            Return CType(Me,ServiceReference1.WebService1Soap).DivisionAsync(inValue)
        End Function
        
        Public Function Inverso(ByVal nro As Double) As Double Implements ServiceReference1.WebService1Soap.Inverso
            Return MyBase.Channel.Inverso(nro)
        End Function
        
        Public Function InversoAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.InversoAsync
            Return MyBase.Channel.InversoAsync(nro)
        End Function
        
        Public Function Factorial(ByVal nro As Integer) As Double Implements ServiceReference1.WebService1Soap.Factorial
            Return MyBase.Channel.Factorial(nro)
        End Function
        
        Public Function FactorialAsync(ByVal nro As Integer) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.FactorialAsync
            Return MyBase.Channel.FactorialAsync(nro)
        End Function
        
        Public Function Potencia(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.Potencia
            Return MyBase.Channel.Potencia(nro1, nro2)
        End Function
        
        Public Function PotenciaAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.PotenciaAsync
            Return MyBase.Channel.PotenciaAsync(nro1, nro2)
        End Function
        
        Public Function Seno(ByVal nro As Double) As Double Implements ServiceReference1.WebService1Soap.Seno
            Return MyBase.Channel.Seno(nro)
        End Function
        
        Public Function SenoAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.SenoAsync
            Return MyBase.Channel.SenoAsync(nro)
        End Function
        
        Public Function Coseno(ByVal nro As Double) As Double Implements ServiceReference1.WebService1Soap.Coseno
            Return MyBase.Channel.Coseno(nro)
        End Function
        
        Public Function CosenoAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.CosenoAsync
            Return MyBase.Channel.CosenoAsync(nro)
        End Function
        
        Public Function Tangente(ByVal nro As Double) As Double Implements ServiceReference1.WebService1Soap.Tangente
            Return MyBase.Channel.Tangente(nro)
        End Function
        
        Public Function TangenteAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.TangenteAsync
            Return MyBase.Channel.TangenteAsync(nro)
        End Function
    End Class
End Namespace
